### ISSUE TITLE
Test suite does not run properly on Mac

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-web-profile-manager#30] opened 2020-05-18 20:06 UTC
Test suite runs properly for me on Ubuntu, but not for @JSAssassin on Mac.

https://gist.github.com/JSAssassin/e954c46510e5f0d04d8501f96325f67b

Maybe this has nothing to do with OS?

**Comment by aljones15** [comment] 2020-05-18 20:11
This is clearly complaining about a babel-react-preset missing.
I think is probably do to @JSAssassin having some type of global config issue.

```js
Built at: 05/18/2020 3:58:02 PM
ℹ ｢wdm｣: Compiled successfully.
[2020-05-18T15:58:03.059] [ERROR] preprocessor.babel - Couldn't find preset "@babel/react" relative to directory "/Users/tashi"
 at /Users/tashi/Desktop/digitalbazaar/bedrock-web-profile-manager/test/web/10-api.js
```

or are we using some react dep in this suite?

**Comment by mattcollier** [comment] 2020-05-21 17:47
@JSAssassin can you pull master here, do a fresh install and try the test suite again.  I think I found the problems as to why it may have been failing for you related to the expectation that there would be an obsolete host mapping for bedrock.localhost which you do not (and should not) have.

**Comment by JSAssassin** [comment] 2020-05-21 18:57
@mattcollier I pulled master and did a fresh install, but I still get the same error.

**Comment by dmitrizagidulin** [comment] 2020-06-22 14:57
This is definitely not a Mac OS X issue; I suspect it has something to do with a missing dependency or config.

**Comment by JSAssassin** [comment] 2020-06-23 12:21
```
npm install karma-babel-preprocessor @babel/core @babel/preset-env --save-dev
```

Installing these dev dependencies solved the problem. Thank you.

**Comment by mattcollier** [comment] 2020-06-23 14:15
@JSAssassin will you be submitting a PR for this fix?  I'm not sure why this does not impact CI and other devs, but these changes seem fine to me.

**Comment by aljones15** [comment] 2020-06-23 14:25
`@babel/preset-env` is huge also no one else is getting this issue so I think the problem is @JSAssassin has a webpack config file somewhere higher up that seems to be for a react project hence the the react failure. the other option is that the local `bedrock-webpack` is not installed. The third option is that webpack or babel is installed globally.

**Comment by JSAssassin** [comment] 2020-06-23 15:36
Turns out there was a .bablerc and .bablerc.json files in home folder, deleted those and now tests run without having to install the dev dependencies. Thank you. Closing this issue.

**Closed by JSAssassin** 2020-06-23 15:36 UTC
